//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int homeworknumber { get; set; }
        public string homeworktitle { get; set; }
        public string homeWork1 { get; set; }
    }
}
